// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRecentProject(arg1:string):Promise<void>;

export function CreateProject(arg1:string,arg2:string):Promise<void>;

export function DeleteAsset(arg1:string,arg2:string):Promise<void>;

export function DeleteDay(arg1:string,arg2:string):Promise<void>;

export function GetDefaultProjectPath():Promise<string>;

export function GetImageBase64(arg1:string,arg2:string):Promise<string>;

export function GetRecentProjects():Promise<Array<string>>;

export function ImportAsset(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ListAssets(arg1:string):Promise<Array<string>>;

export function ListFiles(arg1:string,arg2:string):Promise<Array<string>>;

export function ReadJSON(arg1:string):Promise<string>;

export function SelectFolder():Promise<string>;

export function SelectImageFile():Promise<string>;

export function WriteJSON(arg1:string,arg2:string):Promise<void>;
