// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRecentProject(arg1) {
  return window['go']['main']['App']['AddRecentProject'](arg1);
}

export function CreateProject(arg1, arg2) {
  return window['go']['main']['App']['CreateProject'](arg1, arg2);
}

export function DeleteAsset(arg1, arg2) {
  return window['go']['main']['App']['DeleteAsset'](arg1, arg2);
}

export function DeleteDay(arg1, arg2) {
  return window['go']['main']['App']['DeleteDay'](arg1, arg2);
}

export function DeleteFile(arg1, arg2) {
  return window['go']['main']['App']['DeleteFile'](arg1, arg2);
}

export function GetDefaultProjectPath() {
  return window['go']['main']['App']['GetDefaultProjectPath']();
}

export function GetImageBase64(arg1, arg2) {
  return window['go']['main']['App']['GetImageBase64'](arg1, arg2);
}

export function GetProjectPath() {
  return window['go']['main']['App']['GetProjectPath']();
}

export function GetRecentProjects() {
  return window['go']['main']['App']['GetRecentProjects']();
}

export function ImportAsset(arg1, arg2, arg3) {
  return window['go']['main']['App']['ImportAsset'](arg1, arg2, arg3);
}

export function ImportReactionImage() {
  return window['go']['main']['App']['ImportReactionImage']();
}

export function ListAssets(arg1) {
  return window['go']['main']['App']['ListAssets'](arg1);
}

export function ListFiles(arg1, arg2) {
  return window['go']['main']['App']['ListFiles'](arg1, arg2);
}

export function ReadJSON(arg1) {
  return window['go']['main']['App']['ReadJSON'](arg1);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SelectImageFile() {
  return window['go']['main']['App']['SelectImageFile']();
}

export function SetProjectPath(arg1) {
  return window['go']['main']['App']['SetProjectPath'](arg1);
}

export function WriteJSON(arg1, arg2) {
  return window['go']['main']['App']['WriteJSON'](arg1, arg2);
}
